---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: free5gc-smf-0x01010203
  name: free5gc-smf-0x01010203
spec:
  type: ClusterIP
  ports:
  - name: free5gc-sbi
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: free5gc-n4-0x01010203
    port: 8805
    protocol: UDP
    targetPort: 8805
  selector:
    app: free5gc-smf-0x01010203
